### ISSUE TITLE
Beta putting isn't working

### ISSUE THREAD

**Issue by JustMike70** [mholow/gsp-r10-adapter#10]
Amazing work so far and impressed that you're looking to integrate the putting as well into your connector.  Unfortunately the beta doesn't track the putt. It'll launch the ball tracker when you get to a green and choose a putter, but then nothing happens.  Unless I'm doing something wrong and I'd appreciate any guidance!

**Comment by mholow** [comment]
Closing due to relevance.  For help with the putting software, post issue in https://github.com/alleexx/cam-putting-py or ask about it in the gspro r10-users discord
