### ISSUE TITLE
No flashing green

### ISSUE THREAD

**Issue by fateswarner** [mholow/gsp-r10-adapter#13]
My device flashes blue and never connects, perhaps confirmed by script in adapter "Launch Monitor Is Ready false" per attached screenshot. My gaming PC is new and connects all other bluetooth devices. Might I really need a bluetooth dongle or are there other strategies that you could suggest. Btw, haven't played GSPro since buying licence in Nov 22 cos haven't hooked internet to shed so thanks for your work - there seems to be a minority of us for whom your adapter's not cooperating. 
![Screenshot (1)](https://user-images.githubusercontent.com/128452347/226528402-9ad55d6c-f48e-4215-8fa8-391b3d471737.png)

**Comment by JustMike70** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/114702173/226555790-5619904d-cc71-498a-b88a-2ef5bef9f6d4.png">

I'm no expert but.. Can't see the R10-BT connection message in the screenshot? Do you have the latest version from Github? 

Also, in the settings.json file, check that Bluetooth is enabled and also that the BT name matches what it says in your bluetooth control panel.  Mine for some reason set itself as "Approach R1".

Finally, check the version of Bluetooth that I'm assuming is built into your motherboard.  I've got a v5 BT dongle which was just over £10 from Amazon and that works fine... 

  "bluetooth": {
    "enabled": true,
    "bluetoothDeviceName": "Approach R1",

**Comment by mholow** [comment]
The issue is likely that your exe is not finding the settings.json file and everything is defaulting to disabled. When you download the release you need to unzip both the exe and the json to the same folder. If you want to love the connector to your desktop or something you need to create a shortcut and move that

**Comment by FarOutOfSight** [comment]
I am having a similar issue, the garmin flashes green when its connected but then goes to flashing white. Also, i do not see an option to change bluetooth device name.

**Comment by DennisWes** [comment]
Hi, I have the same issue but today I got one step further when I ran the exe as admin and moved it to the same directory as gspro. But now it stucks after the two purple rows and it says its connected but the next row with battery life doesnt appear.

**Comment by fateswarner** [comment]
Got it working.

It wasn't so much that the exe and file had to be in the same folder (they
are though, cos that's how and where they both download) but which folder
to download to.

I ensured this time that download location was C drive, then randomly chose
Program Files folder. Previously, I'd chosen my PC user downloads folder.
Sort of an administrator versus user (windows 11) issue.

Regards
Peter Warner
***@***.***
M: 0431974699
