### ISSUE TITLE
Does not complete the connection with R10

### ISSUE THREAD

**Issue by DennisWes** [mholow/gsp-r10-adapter#14]
![Github](https://user-images.githubusercontent.com/128702125/227756196-7ab6bbdc-3577-446f-af01-9b961810e706.jpg)

I cant get the connector to complete the setup. It just stucks after it says connected to launch monitor. I also installed windows 11 but it did not help the issue :)

-Dennis

**Comment by mholow** [comment]
Many people reported that this was inadequate Bluetooth strength and solved by either moving the units closer together, removing items between the units or purchasing a better Bluetooth dongle.  Not much I can tell you from the screenshot alone but in the settings.json you can enable “debug logs” for Bluetooth. If you do that and send another screenshot I might be able to tell you for sure

**Comment by DennisWes** [comment]
![github2](https://user-images.githubusercontent.com/128702125/227774235-2836f447-1b46-4b08-bfe5-2a6f1781adbf.jpg)
 This window came up for 2 seconds and then closes.

**Comment by mholow** [comment]
That means there is a problem with how you changes the settings.json file.  I’m talking about this line https://github.com/mholow/gsp-r10-adapter/blob/main/settings.json#L17

change false to true.  If you think you did that correctly, send the full contents of that file and I’ll spot the error

**Comment by mholow** [comment]
“debugLogging”: true,

instead of enabled. Sorry about the confusion

**Comment by DennisWes** [comment]
![github4](https://user-images.githubusercontent.com/128702125/227774944-8ce5bb99-a20f-4868-afbc-c21c2938573a.jpg)
So now then :)

**Comment by mholow** [comment]
Ok so it’s not even getting past the very first few steps of setup. If the r10 is far from the computer try to move it closer and see if that helps. If you’re using an older computer nanny people reported much better success after buying a USB Bluetooth adapter from Amazon. Should be like 10-20 bucks. Just make sure it says Bluetooth low energy (LE) support

**Comment by DennisWes** [comment]
Okey, the R10 has been 0,5m away. Its a 2 year old Asus gaming laptop.

**Comment by mholow** [comment]
In theory that should be fine. Might be worth trying your luck with a usb dongle. Or if you can wait, the next update I release will probably add some logging and error handling to the Bluetooth startup process.   Oh you could also try updating your laptops Bluetooth drivers too if you’re comfortable with that

**Comment by DennisWes** [comment]
Yeah I have updated the bluetooth drivers but did not help. Just to be sure, I got the Gspro a few days ago and never have had the R10 connected via my mobilephone to Gspro and therefore not installed any earlier programs or connectors. This should work without earlier phone connections/sofware?

**Comment by mholow** [comment]
Yeah it should. In the meantime you can try the e6 connection so you can enjoy gspro.   Connect phone to r10 and use e6 server option in the official app

**Comment by DennisWes** [comment]
Ok, thank you for the help so far. I return to you when the dongle arrives in the middle of the week :)

**Comment by DennisWes** [comment]
Hi, unfortunately the new dongle didnt solve the problem :(

**Comment by mholow** [comment]
I’m going to try to work on enhanced debug logging on startup so we can get to the bottom of this. In the meantime you’ll just have to hang tight.  If you haven’t already, ask in the r10-owners channel on the gspro discord. Tons of people there, a few of which have solved your exact problem

**Comment by DennisWes** [comment]
Hi again! Now I got it working after updating the R10 via garmin express and with your latest adapter update. Dont know which one was the trigger but it works! Thanks for your help and for a great software! :)
