### ISSUE TITLE
Having trouble connecting

### ISSUE THREAD

**Issue by StudeSparky** [mholow/gsp-r10-adapter#26]
I am having trouble connecting the r10 adapter to r10 connect. What am I doing wrong?

![20230706_211258](https://github.com/mholow/gsp-r10-adapter/assets/138803604/d7f5cb4b-25bd-4069-aed5-ea38aa272a61)

**Comment by mholow** [comment]
This connector connects directly to gspro (using openconnect/open api option).  No need to use the existing r10 connect program
