### ISSUE TITLE
gsp-r10-adapter opens cam-putting twice 

### ISSUE THREAD

**Issue by MaineMan2012** [mholow/gsp-r10-adapter#30]
Hi, 

I have an issue where gsp-r10-adapter opens cam-putting twice when using "onlyLaunchWhenPutting" set to true. The first window will work and send data but the second window is erroring out. The program will work the first time I select the putter in gspro, but when I select a different club the second window that shows the error doesn't close. So the second I select a putter all windows will open with errors.  When reading the code lines in gsp-r10-adapter seems to be opening the "onlyLaunchWhenPutting" twice. Any ideas as to what going on?

**Comment by alleexx** [comment]
It is fixed in my version until mholow has a chance to accept my pull request 

https://github.com/alleexx/gsp-r10-adapter-fixpath/releases/tag/1.4

**Comment by mholow** [comment]
Just got around to accepting the PR.  Very much appreciate the contribution.
