### ISSUE TITLE
unable to find launch monitor

### ISSUE THREAD

**Issue by nartahn** [mholow/gsp-r10-adapter#5]
I'm unable to get the R10 connected.
I have successfully connected in bluetooth settings.

![Screenshot 2023-03-13 130412](https://user-images.githubusercontent.com/41139475/224595218-91f0d1e3-f268-4ea6-89f6-a9c1943c0917.png)

But I don't get the anticipated handshake.

![Screenshot 2023-03-13 130457](https://user-images.githubusercontent.com/41139475/224595448-f5dcbb04-c55d-4865-b227-8ddfd47e605f.png)

When the r10 is paired for the first time the light turns white for several seconds then the device turns off. When I turn the device back on again it flashes a blue light.
Is the light meant to flash green when it has connected successfully?
I'm running Windows 11 and have tried turning off the firewall and re-paired the r10 multiple times.

**Comment by nartahn** [comment]
I have noticed that my device is registering as 'Approach R1' and in https://github.com/mholow/gsp-r10-adapter/blob/main/src/connections/BluetoothConnection.cs it has a different name.
private static string DEVICE_NAME = "Approach R10";

I'm willing to build the executable again but need a clue on how to do it. Visual Studio Code?

**Comment by mholow** [comment]
Thanks for bringing this to my attention. I debated making device name something that was configurable in the settings file but didn’t expect it to ever not be “Approach R10”. I can put up a quick patch soon to allow that

**Comment by nartahn** [comment]
Thanks for that.
Great job with this as well. It's working a treat. I only started using Gspro 3 days ago and it keeps getting better.

**Comment by JLag1** [comment]
@mholow Hey mate others on my FB post are also having this issue. Not sure where exactly to change the name? Is it in the .JSON or somewhere else?

**Comment by mholow** [comment]
Tell them to hang tight. As of today it’s a constant compiled into the program. I’ll have to post an update later today or tomorrow that allows changing the name on the settings

**Comment by JLag1** [comment]
@mholow thanks mate I passed on the message! And thankyou for all your work you have put and are putting in to this.
