### ISSUE TITLE
Connected to PC but Adapter can't connect

### ISSUE THREAD

**Issue by djmrozinski** [mholow/gsp-r10-adapter#8]
I am able to get the R10 to connect and pair with Windows.  Open GSPro and the API window opens.  When I start the connector software, it just say that it can't connect to the bluetooth device and then repeats every 10 seconds.  Running 2.0.1 

Thoughts??
Thanks
Dave

**Comment by mholow** [comment]
Is the r10 in pairing mode (blue led) at the time you start the connector?  Can you move the r10 closer to your computer just to rule out spotty Bluetooth connection?

**Comment by djmrozinski** [comment]
No it is already connected to the PC. When you look at the BT settings in Windows it says paired. Am I doing something wrong with start up?Does it need to be in pairing mode when I open the adapter?ThanksDaveSent from my iPadOn Mar 14, 2023, at 11:17 AM, mholow ***@***.***> wrote:﻿
Is the r10 in pairing mode (blue led) at the time you start the connector?  Can you move the r10 closer to your computer just to rule out spotty Bluetooth connection?

**Comment by mholow** [comment]
Right you only need to pair with windows once. After the initial pairing, it doesn’t matter what windows says.  Then you should be able to start the connector and turn the device on in pairing mode (or you can turn the device on in pairing mode then start the connector. Either order should work)

**Comment by djmrozinski** [comment]
Hello,

Think I got it.  I had turned BT off on my phone when I was out working on the sim computer.  I forgot about my iPad that was in the house.  I think that the iPad was grabbing the connection before the connector could make the connection.  Once I deleted the R10 from the iPad BT settings it your software connected.

Sorry for sending you on a wild goos chase.  

Great work.
Thanhks
Dave
