### ISSUE TITLE
Flashing white and blue lights from the Garmin after connecting

### ISSUE THREAD

**Issue by JLag1** [mholow/gsp-r10-adapter#9]
Hey Mholow, 

One of my subs is having an issue where: 

everything looks great for connections on the computer, bluetooth paired and connected, GSPro opens fine with the open API, then I open the gsp-r10 connect app, the app goes through its paces, it says connecting to R10 then next line says connected to launch monitor... so everything looks perfect on the computer end. The end result is the R10 flashing quickly white then blue followed by a pause, over and over is all the r10 will do. 

Have you heard of any issues like this or can you think of anything that could be the issue? 

Cheers,

Joe

**Comment by mholow** [comment]
As far as I understand when the computer makes the Bluetooth connection it puts the device in standby mode (white) but then if the device fails the Bluetooth handshake it will disconnect put itself back into pairing mode.  So what’s happening is probably that the computer has some success connecting but trouble keeping steady communication line open
